# Generated by Django 4.1.5 on 2023-09-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_speciality'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
