# Generated by Django 4.1.5 on 2023-09-04 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_speciality'),
        ('manager', '0003_remove_booking_end_remove_booking_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslots',
            name='doctor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
            preserve_default=False,
        ),
    ]
