# Generated by Django 4.1.5 on 2023-09-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_speciality'),
        ('manager', '0004_availableslots_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
