# Generated by Django 4.1.5 on 2023-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_availableslots_booking_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslots',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
