# Generated by Django 4.1.5 on 2023-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_booking_slot_booking_end_booking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='eventid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
