# Generated by Django 4.1.5 on 2023-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ethinicity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
